services:
  aurora-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME:-nvminh162}/aurora-backend:latest"
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - aurora-network

networks:
  aurora-network:
    driver: bridge
